apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-2
  version: "1.22"

vpc:
  cidr: 10.0.0.0/16

managedNodeGroups:
  - name: ng-0
    instanceType: c5.xlarge
    desiredCapacity: 4
    minSize: 4
    maxSize: 30
    volumeSize: 20
