apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster-dev
  region: us-east-2
  version: "1.22"

vpc:
  cidr: 10.10.0.0/16

managedNodeGroups:
  - name: ng-0
    instanceType: c5.xlarge
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    volumeSize: 20
